### ISSUE TITLE
Плашку Яндекс.Метрики, zero.kz и Liveinternet.ru поставить по центру на КАЖДУЮ страницу.

### ISSUE THREAD

**Issue by KokTis** [DefaultInc/fit_kbtu-front-end#30]
3 информера в footer

**Comment by NurlashKO** [comment]
Hi KokTis, 

Thank you for creating an issue.

Wouldn't Google Analytics be enough?
Actually, we already have it for gathering the data.

Should we share our user activity with others?
Best,
Nurlan

**Comment by KokTis** [comment]
GA has no visible informer.
We need Yandex.Metrika in order to monitor amount of users.
